/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SQLite;
import Model.User;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beepxD
 */
public class MgmtUser extends javax.swing.JPanel {

    public SQLite sqlite;
    public Frame frame;
    public DefaultTableModel tableModel;
    
    public MgmtUser(SQLite sqlite) {
        initComponents();
        this.sqlite = sqlite;
        tableModel = (DefaultTableModel)table.getModel();
        table.getTableHeader().setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 14));
        
//        UNCOMMENT TO DISABLE BUTTONS
//        editBtn.setVisible(false);
//        deleteBtn.setVisible(false);
//        lockBtn.setVisible(false);
//        chgpassBtn.setVisible(false);
    }
    
    public void init(){
        //      CLEAR TABLE
        for(int nCtr = tableModel.getRowCount(); nCtr > 0; nCtr--){
            tableModel.removeRow(0);
        }
        
//      LOAD CONTENTS
        ArrayList<User> users = sqlite.getUsers();
        for(int nCtr = 0; nCtr < users.size(); nCtr++){
            tableModel.addRow(new Object[]{
                users.get(nCtr).getUsername(), 
                users.get(nCtr).getPassword(), 
                users.get(nCtr).getRole(), 
                users.get(nCtr).getLocked()});
        }
    }

    public void designer(JTextField component, String text){
        component.setSize(70, 600);
        component.setFont(new java.awt.Font("Tahoma", 0, 18));
        component.setBackground(new java.awt.Color(240, 240, 240));
        component.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        component.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), text, javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        editRoleBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        lockBtn = new javax.swing.JButton();
        chgpassBtn = new javax.swing.JButton();

        table.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Role", "Locked"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(24);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(160);
            table.getColumnModel().getColumn(1).setPreferredWidth(400);
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
            table.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        editRoleBtn.setBackground(new java.awt.Color(255, 255, 255));
        editRoleBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editRoleBtn.setText("EDIT ROLE");
        editRoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoleBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        lockBtn.setBackground(new java.awt.Color(255, 255, 255));
        lockBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lockBtn.setText("LOCK/UNLOCK");
        lockBtn.setToolTipText("");
        lockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockBtnActionPerformed(evt);
            }
        });

        chgpassBtn.setBackground(new java.awt.Color(255, 255, 255));
        chgpassBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chgpassBtn.setText("CHANGE PASS");
        chgpassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chgpassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editRoleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(lockBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(chgpassBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chgpassBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoleBtnActionPerformed
        if (frame == null) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Session error.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; 
        }
        if (!frame.checkAccess(5)) return;
        
        if(table.getSelectedRow() >= 0){
            String[] options = {"1-DISABLED","2-CLIENT","3-STAFF","4-MANAGER","5-ADMIN"};
            JComboBox optionList = new JComboBox(options);
            
            optionList.setSelectedIndex((int)tableModel.getValueAt(table.getSelectedRow(), 2) - 1);
            
            String result = (String) JOptionPane.showInputDialog(null, "USER: " + tableModel.getValueAt(table.getSelectedRow(), 0), 
                "EDIT USER ROLE", JOptionPane.QUESTION_MESSAGE, null, options, options[(int)tableModel.getValueAt(table.getSelectedRow(), 2) - 1]);
            
            if(result != null){
               int newRole = Integer.parseInt(result.substring(0, 1));
               if (newRole < 1 || newRole > 5) {
                   JOptionPane.showMessageDialog(null, "Invalid role.");
                   return;
               }
               String targetUser = (String) tableModel.getValueAt(table.getSelectedRow(), 0);
               sqlite.updateUserRole(targetUser, newRole);
               sqlite.addLogs("ROLE_CHANGE", targetUser, "Role changed to " + newRole, 
                       new java.sql.Timestamp(new java.util.Date().getTime()).toString());
               init();
            }
        }
    }//GEN-LAST:event_editRoleBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if (frame == null) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Session error.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; 
        }
        if (!frame.checkAccess(5)) return;
        
        if(table.getSelectedRow() >= 0){
            int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + tableModel.getValueAt(table.getSelectedRow(), 0) + "?", "DELETE USER", JOptionPane.YES_NO_OPTION);
            
            if (result == JOptionPane.YES_OPTION) {
                String targetUser = (String) tableModel.getValueAt(table.getSelectedRow(), 0);
                sqlite.removeUser(targetUser);
                sqlite.addLogs("USER_DELETE", targetUser, "User deleted", 
                        new java.sql.Timestamp(new java.util.Date().getTime()).toString());
                init();
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void lockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockBtnActionPerformed
        if (frame == null) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Session error.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; 
        }
        if (!frame.checkAccess(5)) return;
        
        if(table.getSelectedRow() >= 0){
            String state = "lock";
            if("1".equals(tableModel.getValueAt(table.getSelectedRow(), 3) + "")){
                state = "unlock";
            }
            
            int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to " + state + " " + tableModel.getValueAt(table.getSelectedRow(), 0) + "?", "DELETE USER", JOptionPane.YES_NO_OPTION);
            
            if (result == JOptionPane.YES_OPTION) {
               String targetUser = (String) tableModel.getValueAt(table.getSelectedRow(), 0);
               int currentLocked = Integer.parseInt(tableModel.getValueAt(table.getSelectedRow(), 3) + "");
               if (currentLocked == 1) {
                   sqlite.toggleUserLock(targetUser, 0, 2);
               } else {
                   sqlite.toggleUserLock(targetUser, 1, 1);
               }
               sqlite.addLogs("LOCK_TOGGLE", targetUser, "Account" + (currentLocked == 1 ? "unlocked" : "locked"),
                       new java.sql.Timestamp(new java.util.Date().getTime()).toString());
               init();
            }
        }
    }//GEN-LAST:event_lockBtnActionPerformed

    private void chgpassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chgpassBtnActionPerformed
        if (frame == null) { 
            javax.swing.JOptionPane.showMessageDialog(this, "Session error.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; 
        }
        if (!frame.checkAccess(5)) return;
        
        if(table.getSelectedRow() >= 0){
            String targetUser = (String) tableModel.getValueAt(table.getSelectedRow(), 0);
            
            JPasswordField currentPassFld = new JPasswordField();
            designer(currentPassFld, "CURRENT PASSWORD");
            
            int reAuthResult = JOptionPane.showConfirmDialog(null, 
                    new Object[]{"Re-authentication required.\nEnter CURRENT passwrod for: " + targetUser, currentPassFld},
                    "Re-Authentiation", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null);
            
            if (reAuthResult != JOptionPane.OK_OPTION) return;
            
            String currentPass = new String(currentPassFld.getPassword());
            Model.User target = null;
            
            try {
                target = sqlite.getUser(targetUser);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error retrievng user data.");
                return;
            }
            
            if (target == null || !Controller.PasswordUtil.verifyPassword(currentPass, target.getPassword())) {
                JOptionPane.showMessageDialog(null, 
                        "Re-authentication failed.",
                        "Access Denied", JOptionPane.WARNING_MESSAGE);
                sqlite.addLogs("REAUTH_FAIL", targetUser,
                        "Failed re-authentication before password change",
                        new java.sql.Timestamp(new java.util.Date().getTime()).toString());
                return;
            }
            
            JPasswordField newPassFld = new JPasswordField();
            JPasswordField confPassFld = new JPasswordField();
            designer(newPassFld, "NEW PASSWORD");
            designer(confPassFld, "CONFIRM PASSWORD");
            
            int result = JOptionPane.showConfirmDialog(null,
                    new Object[]{"Enter New Password:", newPassFld, "Confirm Password:", confPassFld},
                    "Change Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE, null);
            
            if (result != JOptionPane.OK_OPTION) return;
            
            String newPass = new String(newPassFld.getPassword());
            String confPass = new String(confPassFld.getPassword());
            
            if (newPass.length() < 8 || newPass.length() > 64) {
                JOptionPane.showMessageDialog(null, 
                        "Password must be between 8 and 64 characters.", 
                        "Validation Error", JOptionPane.WARNING_MESSAGE);
                sqlite.addLogs("VALIDATION_FAIL", targetUser, 
                        "Password change: length out of range",
                        new java.sql.Timestamp(new java.util.Date().getTime()).toString());
                return;
            }
            
            boolean hasUpper = java.util.regex.Pattern.compile("[A-Z]").matcher(newPass).find();
            boolean hasLower = java.util.regex.Pattern.compile("[a-z]").matcher(newPass).find();
            boolean hasDigit = java.util.regex.Pattern.compile("[0-9]").matcher(newPass).find();
            boolean hasSpecial = java.util.regex.Pattern.compile("[^a-zA-Z0-9]").matcher(newPass).find();
            
            if (!hasUpper || !hasLower || !hasDigit || !hasSpecial) {
                JOptionPane.showMessageDialog(null,
                        "Password must contain at least one uppercase letter, \n" 
                        + "one lowercase letter, one digit, and one special character.",
                        "Validation Error", JOptionPane.WARNING_MESSAGE);
                sqlite.addLogs("VALIDATION_FAIL", targetUser, 
                        "Password change: does not meet policy requirements",
                        new java.sql.Timestamp(new java.util.Date().getTime()).toString());
                return;
            }
            
            if (!newPass.equals(confPass)) {
                JOptionPane.showMessageDialog(null,
                        "Passwords do not match.",
                        "Validation Error", JOptionPane.WARNING_MESSAGE);
                sqlite.addLogs("VALIDATION_FAIL", targetUser,
                        "Password change: confirmation mismatch",
                        new java.sql.Timestamp(new java.util.Date().getTime()).toString());
                return;
            }
            
            try {
                String hashed = Controller.PasswordUtil.hashPassword(newPass);
                sqlite.updateUserPassword(targetUser, hashed);
                sqlite.addLogs("PASS_CHANGE", targetUser, 
                        "Password successfully changed by admin", 
                        new java.sql.Timestamp(new java.util.Date().getTime()).toString());
                JOptionPane.showMessageDialog(null,
                        "Password changed successfully.",
                        "Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,
                        "An unexpected error occured. Please try again.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_chgpassBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chgpassBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editRoleBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lockBtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
